import { displayFont, bodyFont } from "@/lib/fonts";
import MotionBackdrop from "@/components/motion/MotionBackdrop.jsx";
import SmoothScroll from "@/components/motion/SmoothScroll.jsx";
import SiteHeader from "@/components/layout/SiteHeader.jsx";
import SiteFooter from "@/components/layout/SiteFooter.jsx";
import ChromeGate from "@/components/layout/ChromeGate.jsx";
import "./globals.css";
import { cn } from "@/lib/utils";

export const metadata = {
  title: "ARAH — Post-SPM Pathway Finder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", displayFont.variable, bodyFont.variable, "font-sans")}
    >
      <body className="min-h-full flex flex-col">
        {/* Motion backdrop: ParticleField at z-0, CursorSpotlight at z-1.
            Siblings behind the content, never inside it, so they never
            participate in document flow or layout. Loaded lazily and skipped
            on /admin entirely — see MotionBackdrop. */}
        <MotionBackdrop />
        {/* Content gets its own stacking context above both layers. */}
        <SmoothScroll>
          {/* Global chrome: header and footer wrap every page except /admin,
              which supplies its own via AdminShell. ChromeGate makes that
              call client-side on purpose — this layout does NOT re-render on
              client navigation, so deciding it here from a request header
              left two headers stacked after navigating into /admin, and no
              header at all after navigating back out. See ChromeGate's own
              comment for the measurements. Both read the session server-side
              through the shared, cached getViewer(). */}
          <div className="relative z-[2] flex min-h-full flex-1 flex-col">
            <ChromeGate>
              <SiteHeader />
            </ChromeGate>
            {children}
            <ChromeGate>
              <SiteFooter />
            </ChromeGate>
          </div>
        </SmoothScroll>
      </body>
    </html>
  );
}
