import { displayFont, bodyFont } from "@/lib/fonts";
import ParticleField from "@/components/motion/ParticleField.jsx";
import CursorSpotlight from "@/components/motion/CursorSpotlight.jsx";
import SmoothScroll from "@/components/motion/SmoothScroll.jsx";
import SiteHeader from "@/components/layout/SiteHeader.jsx";
import SiteFooter from "@/components/layout/SiteFooter.jsx";
import "./globals.css";
import { cn } from "@/lib/utils";

export const metadata = {
  title: "ARAH — Post-SPM Pathway Finder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", displayFont.variable, bodyFont.variable, "font-sans")}
    >
      <body className="min-h-full flex flex-col">
        {/* Motion backdrop layers: ParticleField at z-0, CursorSpotlight at
            z-1. Both are siblings behind the content, never inside it, so
            they never participate in document flow or layout. */}
        <ParticleField />
        <CursorSpotlight />
        {/* Content gets its own stacking context above both layers. */}
        <SmoothScroll>
          {/* Global chrome (Task 7): header and footer wrap every page.
              Both read the session server-side through the shared, cached
              getViewer() — one auth check per request between them. */}
          <div className="relative z-[2] flex min-h-full flex-1 flex-col">
            <SiteHeader />
            {children}
            <SiteFooter />
          </div>
        </SmoothScroll>
      </body>
    </html>
  );
}
