import { displayFont, bodyFont } from "@/lib/fonts";
import "./globals.css";

export const metadata = {
  title: "ARAH — Post-SPM Pathway Finder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${displayFont.variable} ${bodyFont.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
